In [1]:
import numpy as np

# np.newaxis Attribute : Expanding Dimension

In [2]:
a=np.arange(5)
print(a)
print(a.shape)

[0 1 2 3 4]
(5,)


In [4]:
row_vector=a.reshape((1,-1)) #> a.reshape((1,5))
print(row_vector)
print(row_vector.shape)

[[0 1 2 3 4]]
(1, 5)


In [6]:
column_vector=a.reshape((-1,1)) #> a.reshape((5,1))
print(column_vector)
print(column_vector.shape)

[[0]
 [1]
 [2]
 [3]
 [4]]
(5, 1)


In [7]:
a[:]

array([0, 1, 2, 3, 4])

In [8]:
a[:, np.newaxis] #> column vector

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [9]:
a[np.newaxis, :] #> row vector

array([[0, 1, 2, 3, 4]])

In [10]:
a=np.arange(6).reshape((2,3))
a

array([[0, 1, 2],
       [3, 4, 5]])

In [11]:
a[:,:] # (2,3) shape

array([[0, 1, 2],
       [3, 4, 5]])

In [12]:
a[np.newaxis, :, :] # (1,2,3) shape

array([[[0, 1, 2],
        [3, 4, 5]]])

In [13]:
a[:, :, np.newaxis] # (2,3,1) shape

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [14]:
a[:, np.newaxis, :] # (2,1,3) shape

array([[[0, 1, 2]],

       [[3, 4, 5]]])